title: Loukaki Youkaki
author: Ioannis Loukidis
email: yloukidis@gmail.com
theme: minima

description: > # this means to ignore newlines until "baseurl:"
  I CAN NOT BE HELD RESPNSIBLE FOR WHAT MY FACE DOES WHEN YOU TALK. 

# social links
twitter_username: VulcanLoL # DO NOT include the @ character, or else the build will fail!
github_username:  YoukaLouka # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
